/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.tables.records;


import java.math.BigDecimal;

import javax.annotation.processing.Generated;

import jooq.steve.db.tables.ChargingProfile;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.1",
        "schema version:1.0.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChargingProfileRecord extends UpdatableRecordImpl<ChargingProfileRecord> implements Record13<Integer, Integer, String, String, String, DateTime, DateTime, Integer, DateTime, String, BigDecimal, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stevedb.charging_profile.charging_profile_pk</code>.
     */
    public ChargingProfileRecord setChargingProfilePk(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.charging_profile_pk</code>.
     */
    public Integer getChargingProfilePk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stevedb.charging_profile.stack_level</code>.
     */
    public ChargingProfileRecord setStackLevel(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.stack_level</code>.
     */
    public Integer getStackLevel() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>stevedb.charging_profile.charging_profile_purpose</code>.
     */
    public ChargingProfileRecord setChargingProfilePurpose(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>stevedb.charging_profile.charging_profile_purpose</code>.
     */
    public String getChargingProfilePurpose() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stevedb.charging_profile.charging_profile_kind</code>.
     */
    public ChargingProfileRecord setChargingProfileKind(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.charging_profile_kind</code>.
     */
    public String getChargingProfileKind() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stevedb.charging_profile.recurrency_kind</code>.
     */
    public ChargingProfileRecord setRecurrencyKind(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.recurrency_kind</code>.
     */
    public String getRecurrencyKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stevedb.charging_profile.valid_from</code>.
     */
    public ChargingProfileRecord setValidFrom(DateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.valid_from</code>.
     */
    public DateTime getValidFrom() {
        return (DateTime) get(5);
    }

    /**
     * Setter for <code>stevedb.charging_profile.valid_to</code>.
     */
    public ChargingProfileRecord setValidTo(DateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.valid_to</code>.
     */
    public DateTime getValidTo() {
        return (DateTime) get(6);
    }

    /**
     * Setter for <code>stevedb.charging_profile.duration_in_seconds</code>.
     */
    public ChargingProfileRecord setDurationInSeconds(Integer value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.duration_in_seconds</code>.
     */
    public Integer getDurationInSeconds() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>stevedb.charging_profile.start_schedule</code>.
     */
    public ChargingProfileRecord setStartSchedule(DateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.start_schedule</code>.
     */
    public DateTime getStartSchedule() {
        return (DateTime) get(8);
    }

    /**
     * Setter for <code>stevedb.charging_profile.charging_rate_unit</code>.
     */
    public ChargingProfileRecord setChargingRateUnit(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.charging_rate_unit</code>.
     */
    public String getChargingRateUnit() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stevedb.charging_profile.min_charging_rate</code>.
     */
    public ChargingProfileRecord setMinChargingRate(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.min_charging_rate</code>.
     */
    public BigDecimal getMinChargingRate() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>stevedb.charging_profile.description</code>.
     */
    public ChargingProfileRecord setDescription(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.description</code>.
     */
    public String getDescription() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stevedb.charging_profile.note</code>.
     */
    public ChargingProfileRecord setNote(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.charging_profile.note</code>.
     */
    public String getNote() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, String, String, String, DateTime, DateTime, Integer, DateTime, String, BigDecimal, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, String, String, String, DateTime, DateTime, Integer, DateTime, String, BigDecimal, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChargingProfile.CHARGING_PROFILE.CHARGING_PROFILE_PK;
    }

    @Override
    public Field<Integer> field2() {
        return ChargingProfile.CHARGING_PROFILE.STACK_LEVEL;
    }

    @Override
    public Field<String> field3() {
        return ChargingProfile.CHARGING_PROFILE.CHARGING_PROFILE_PURPOSE;
    }

    @Override
    public Field<String> field4() {
        return ChargingProfile.CHARGING_PROFILE.CHARGING_PROFILE_KIND;
    }

    @Override
    public Field<String> field5() {
        return ChargingProfile.CHARGING_PROFILE.RECURRENCY_KIND;
    }

    @Override
    public Field<DateTime> field6() {
        return ChargingProfile.CHARGING_PROFILE.VALID_FROM;
    }

    @Override
    public Field<DateTime> field7() {
        return ChargingProfile.CHARGING_PROFILE.VALID_TO;
    }

    @Override
    public Field<Integer> field8() {
        return ChargingProfile.CHARGING_PROFILE.DURATION_IN_SECONDS;
    }

    @Override
    public Field<DateTime> field9() {
        return ChargingProfile.CHARGING_PROFILE.START_SCHEDULE;
    }

    @Override
    public Field<String> field10() {
        return ChargingProfile.CHARGING_PROFILE.CHARGING_RATE_UNIT;
    }

    @Override
    public Field<BigDecimal> field11() {
        return ChargingProfile.CHARGING_PROFILE.MIN_CHARGING_RATE;
    }

    @Override
    public Field<String> field12() {
        return ChargingProfile.CHARGING_PROFILE.DESCRIPTION;
    }

    @Override
    public Field<String> field13() {
        return ChargingProfile.CHARGING_PROFILE.NOTE;
    }

    @Override
    public Integer component1() {
        return getChargingProfilePk();
    }

    @Override
    public Integer component2() {
        return getStackLevel();
    }

    @Override
    public String component3() {
        return getChargingProfilePurpose();
    }

    @Override
    public String component4() {
        return getChargingProfileKind();
    }

    @Override
    public String component5() {
        return getRecurrencyKind();
    }

    @Override
    public DateTime component6() {
        return getValidFrom();
    }

    @Override
    public DateTime component7() {
        return getValidTo();
    }

    @Override
    public Integer component8() {
        return getDurationInSeconds();
    }

    @Override
    public DateTime component9() {
        return getStartSchedule();
    }

    @Override
    public String component10() {
        return getChargingRateUnit();
    }

    @Override
    public BigDecimal component11() {
        return getMinChargingRate();
    }

    @Override
    public String component12() {
        return getDescription();
    }

    @Override
    public String component13() {
        return getNote();
    }

    @Override
    public Integer value1() {
        return getChargingProfilePk();
    }

    @Override
    public Integer value2() {
        return getStackLevel();
    }

    @Override
    public String value3() {
        return getChargingProfilePurpose();
    }

    @Override
    public String value4() {
        return getChargingProfileKind();
    }

    @Override
    public String value5() {
        return getRecurrencyKind();
    }

    @Override
    public DateTime value6() {
        return getValidFrom();
    }

    @Override
    public DateTime value7() {
        return getValidTo();
    }

    @Override
    public Integer value8() {
        return getDurationInSeconds();
    }

    @Override
    public DateTime value9() {
        return getStartSchedule();
    }

    @Override
    public String value10() {
        return getChargingRateUnit();
    }

    @Override
    public BigDecimal value11() {
        return getMinChargingRate();
    }

    @Override
    public String value12() {
        return getDescription();
    }

    @Override
    public String value13() {
        return getNote();
    }

    @Override
    public ChargingProfileRecord value1(Integer value) {
        setChargingProfilePk(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value2(Integer value) {
        setStackLevel(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value3(String value) {
        setChargingProfilePurpose(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value4(String value) {
        setChargingProfileKind(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value5(String value) {
        setRecurrencyKind(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value6(DateTime value) {
        setValidFrom(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value7(DateTime value) {
        setValidTo(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value8(Integer value) {
        setDurationInSeconds(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value9(DateTime value) {
        setStartSchedule(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value10(String value) {
        setChargingRateUnit(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value11(BigDecimal value) {
        setMinChargingRate(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value12(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ChargingProfileRecord value13(String value) {
        setNote(value);
        return this;
    }

    @Override
    public ChargingProfileRecord values(Integer value1, Integer value2, String value3, String value4, String value5, DateTime value6, DateTime value7, Integer value8, DateTime value9, String value10, BigDecimal value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChargingProfileRecord
     */
    public ChargingProfileRecord() {
        super(ChargingProfile.CHARGING_PROFILE);
    }

    /**
     * Create a detached, initialised ChargingProfileRecord
     */
    public ChargingProfileRecord(Integer chargingProfilePk, Integer stackLevel, String chargingProfilePurpose, String chargingProfileKind, String recurrencyKind, DateTime validFrom, DateTime validTo, Integer durationInSeconds, DateTime startSchedule, String chargingRateUnit, BigDecimal minChargingRate, String description, String note) {
        super(ChargingProfile.CHARGING_PROFILE);

        setChargingProfilePk(chargingProfilePk);
        setStackLevel(stackLevel);
        setChargingProfilePurpose(chargingProfilePurpose);
        setChargingProfileKind(chargingProfileKind);
        setRecurrencyKind(recurrencyKind);
        setValidFrom(validFrom);
        setValidTo(validTo);
        setDurationInSeconds(durationInSeconds);
        setStartSchedule(startSchedule);
        setChargingRateUnit(chargingRateUnit);
        setMinChargingRate(minChargingRate);
        setDescription(description);
        setNote(note);
    }
}
