/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.tables.records;


import javax.annotation.processing.Generated;

import jooq.steve.db.enums.TransactionStopFailedEventActor;
import jooq.steve.db.tables.TransactionStopFailed;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7",
        "schema version:1.0.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionStopFailedRecord extends TableRecordImpl<TransactionStopFailedRecord> implements Record8<Integer, String, DateTime, TransactionStopFailedEventActor, DateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stevedb.transaction_stop_failed.transaction_pk</code>.
     */
    public TransactionStopFailedRecord setTransactionPk(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.transaction_pk</code>.
     */
    public Integer getTransactionPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.charge_box_id</code>.
     */
    public TransactionStopFailedRecord setChargeBoxId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.charge_box_id</code>.
     */
    public String getChargeBoxId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.event_timestamp</code>.
     */
    public TransactionStopFailedRecord setEventTimestamp(DateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.event_timestamp</code>.
     */
    public DateTime getEventTimestamp() {
        return (DateTime) get(2);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.event_actor</code>.
     */
    public TransactionStopFailedRecord setEventActor(TransactionStopFailedEventActor value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.event_actor</code>.
     */
    public TransactionStopFailedEventActor getEventActor() {
        return (TransactionStopFailedEventActor) get(3);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.stop_timestamp</code>.
     */
    public TransactionStopFailedRecord setStopTimestamp(DateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.stop_timestamp</code>.
     */
    public DateTime getStopTimestamp() {
        return (DateTime) get(4);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.stop_value</code>.
     */
    public TransactionStopFailedRecord setStopValue(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.stop_value</code>.
     */
    public String getStopValue() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.stop_reason</code>.
     */
    public TransactionStopFailedRecord setStopReason(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.stop_reason</code>.
     */
    public String getStopReason() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stevedb.transaction_stop_failed.fail_reason</code>.
     */
    public TransactionStopFailedRecord setFailReason(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.transaction_stop_failed.fail_reason</code>.
     */
    public String getFailReason() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, DateTime, TransactionStopFailedEventActor, DateTime, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, DateTime, TransactionStopFailedEventActor, DateTime, String, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.TRANSACTION_PK;
    }

    @Override
    public Field<String> field2() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.CHARGE_BOX_ID;
    }

    @Override
    public Field<DateTime> field3() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.EVENT_TIMESTAMP;
    }

    @Override
    public Field<TransactionStopFailedEventActor> field4() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.EVENT_ACTOR;
    }

    @Override
    public Field<DateTime> field5() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.STOP_TIMESTAMP;
    }

    @Override
    public Field<String> field6() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.STOP_VALUE;
    }

    @Override
    public Field<String> field7() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.STOP_REASON;
    }

    @Override
    public Field<String> field8() {
        return TransactionStopFailed.TRANSACTION_STOP_FAILED.FAIL_REASON;
    }

    @Override
    public Integer component1() {
        return getTransactionPk();
    }

    @Override
    public String component2() {
        return getChargeBoxId();
    }

    @Override
    public DateTime component3() {
        return getEventTimestamp();
    }

    @Override
    public TransactionStopFailedEventActor component4() {
        return getEventActor();
    }

    @Override
    public DateTime component5() {
        return getStopTimestamp();
    }

    @Override
    public String component6() {
        return getStopValue();
    }

    @Override
    public String component7() {
        return getStopReason();
    }

    @Override
    public String component8() {
        return getFailReason();
    }

    @Override
    public Integer value1() {
        return getTransactionPk();
    }

    @Override
    public String value2() {
        return getChargeBoxId();
    }

    @Override
    public DateTime value3() {
        return getEventTimestamp();
    }

    @Override
    public TransactionStopFailedEventActor value4() {
        return getEventActor();
    }

    @Override
    public DateTime value5() {
        return getStopTimestamp();
    }

    @Override
    public String value6() {
        return getStopValue();
    }

    @Override
    public String value7() {
        return getStopReason();
    }

    @Override
    public String value8() {
        return getFailReason();
    }

    @Override
    public TransactionStopFailedRecord value1(Integer value) {
        setTransactionPk(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value2(String value) {
        setChargeBoxId(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value3(DateTime value) {
        setEventTimestamp(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value4(TransactionStopFailedEventActor value) {
        setEventActor(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value5(DateTime value) {
        setStopTimestamp(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value6(String value) {
        setStopValue(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value7(String value) {
        setStopReason(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord value8(String value) {
        setFailReason(value);
        return this;
    }

    @Override
    public TransactionStopFailedRecord values(Integer value1, String value2, DateTime value3, TransactionStopFailedEventActor value4, DateTime value5, String value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionStopFailedRecord
     */
    public TransactionStopFailedRecord() {
        super(TransactionStopFailed.TRANSACTION_STOP_FAILED);
    }

    /**
     * Create a detached, initialised TransactionStopFailedRecord
     */
    public TransactionStopFailedRecord(Integer transactionPk, String chargeBoxId, DateTime eventTimestamp, TransactionStopFailedEventActor eventActor, DateTime stopTimestamp, String stopValue, String stopReason, String failReason) {
        super(TransactionStopFailed.TRANSACTION_STOP_FAILED);

        setTransactionPk(transactionPk);
        setChargeBoxId(chargeBoxId);
        setEventTimestamp(eventTimestamp);
        setEventActor(eventActor);
        setStopTimestamp(stopTimestamp);
        setStopValue(stopValue);
        setStopReason(stopReason);
        setFailReason(failReason);
    }
}
