package de.rwth.idsg.steve;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.rwth.idsg.sensor.change.ChangeConfigurationRequest;
import de.rwth.idsg.sensor.change.ChangeConfigurationResponse;
import de.rwth.idsg.sensor.change.ChangeService;
import de.rwth.idsg.sensor.change.ChangeStatusRequest;
import de.rwth.idsg.sensor.change.ChangeStatusResponse;
import de.rwth.idsg.sensor.change.Status;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Sep 17 17:11:43 CEST 2013
 * Generated source version: 2.3.1
 * 
 */
public final class ChangeService_Client {

	private static final Logger LOG = LoggerFactory.getLogger(ChangeService_Client.class);
	private static JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();

	static {
		factory.setServiceClass(ChangeService.class);
	}	

	/////// CREATE and SEND Request Payloads /////// 
	
	public void sendChangeConfiguration(String chargeBoxId, String endpoint_address, int timeoutValue){
		LOG.info("[SENSOR] Invoking changeConfiguration...");
		
		ChangeConfigurationRequest req = new ChangeConfigurationRequest();
		req.setTimeoutValue(timeoutValue);
		
		factory.setAddress(endpoint_address);
		ChangeService client = (ChangeService) factory.create();
		ChangeConfigurationResponse response = client.changeConfiguration(req, chargeBoxId);
		LOG.info("[SENSOR] Charge point: " + chargeBoxId + ", Request: new timeoutValue=" + timeoutValue  + ", Response: " + response.isConfigChanged());
	}

	public void sendChangeStatus(String chargeBoxId, String endpoint_address, int connectorId, Status status){
		LOG.info("[SENSOR] Invoking changeStatus...");
		
		ChangeStatusRequest req = new ChangeStatusRequest();
		req.setConnectorId(connectorId);
		req.setStatus(status);
		
		factory.setAddress(endpoint_address);
		ChangeService client = (ChangeService) factory.create();
		ChangeStatusResponse response = client.changeStatus(req, chargeBoxId);
		LOG.info("[SENSOR] Charge point: " + chargeBoxId + ", connectorId: " + connectorId + " / Request: new status=" + status.toString() + ", Response:" + response.isStatusChanged());
	}
}
