/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.enums;


import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7",
        "schema version:1.0.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TransactionStopEventActor implements EnumType {

    station("station"),

    manual("manual");

    private final String literal;

    private TransactionStopEventActor(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "transaction_stop_event_actor";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static TransactionStopEventActor lookupLiteral(String literal) {
        return EnumType.lookupLiteral(TransactionStopEventActor.class, literal);
    }
}
