/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.enums;


import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.1",
        "schema version:1.0.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TransactionStopFailedEventActor implements EnumType {

    station("station"),

    manual("manual");

    private final String literal;

    private TransactionStopFailedEventActor(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "transaction_stop_failed_event_actor";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
