
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.rwth.idsg.sensor.inform;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Sep 18 17:43:14 CEST 2013
 * Generated source version: 2.3.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "InformService",
                      portName = "InformServiceSOAP12",
                      targetNamespace = "urn://de/rwth/idsg/sensor/inform",
                      wsdlLocation = "file:/Users/sgokay/git/steve/src/main/webapp/SensorInformService.wsdl",
                      endpointInterface = "de.rwth.idsg.sensor.inform.InformService")
                      
public class InformServiceImpl implements InformService {

    private static final Logger LOG = Logger.getLogger(InformServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see de.rwth.idsg.sensor.inform.InformService#informParking(de.rwth.idsg.sensor.inform.InformParkingRequest  parameters ,)java.lang.String  chargeBoxIdentity )*
     */
    public de.rwth.idsg.sensor.inform.InformParkingResponse informParking(InformParkingRequest parameters,java.lang.String chargeBoxIdentity) { 
        LOG.info("Executing operation informParking");
        System.out.println(parameters);
        System.out.println(chargeBoxIdentity);
        try {
            de.rwth.idsg.sensor.inform.InformParkingResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
