package de.rwth.idsg.sensor.inform;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Oct 08 12:40:56 CEST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "urn://de/rwth/idsg/sensor/inform/", name = "InformService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InformService {

    @WebResult(name = "InformParkingResponse", targetNamespace = "urn://de/rwth/idsg/sensor/inform/", partName = "parameters")
    @WebMethod(operationName = "InformParking", action = "/InformParking")
    public InformParkingResponse informParking(
        @WebParam(partName = "parameters", name = "InformParkingRequest", targetNamespace = "urn://de/rwth/idsg/sensor/inform/")
        InformParkingRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "ChargeBoxIdentity", targetNamespace = "urn://de/rwth/idsg/sensor/inform/", header = true)
        java.lang.String chargeBoxIdentity
    );
}
