package de.rwth.idsg.sensor.change;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Sep 18 17:45:53 CEST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "urn://de/rwth/idsg/sensor/change", name = "ChangeService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChangeService {

    @WebResult(name = "ChangeConfigurationResponse", targetNamespace = "urn://de/rwth/idsg/sensor/change", partName = "parameters")
    @WebMethod(operationName = "ChangeConfiguration", action = "/ChangeConfiguration")
    public ChangeConfigurationResponse changeConfiguration(
        @WebParam(partName = "parameters", name = "ChangeConfigurationRequest", targetNamespace = "urn://de/rwth/idsg/sensor/change")
        ChangeConfigurationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "ChargeBoxIdentity", targetNamespace = "urn://de/rwth/idsg/sensor/change", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "ChangeStatusResponse", targetNamespace = "urn://de/rwth/idsg/sensor/change", partName = "parameters")
    @WebMethod(operationName = "ChangeStatus", action = "/ChangeStatus")
    public ChangeStatusResponse changeStatus(
        @WebParam(partName = "parameters", name = "ChangeStatusRequest", targetNamespace = "urn://de/rwth/idsg/sensor/change")
        ChangeStatusRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "ChargeBoxIdentity", targetNamespace = "urn://de/rwth/idsg/sensor/change", header = true)
        java.lang.String chargeBoxIdentity
    );
}
