
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.rwth.idsg.sensor.change;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Sep 18 17:45:53 CEST 2013
 * Generated source version: 2.3.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ChangeService",
                      portName = "ChangeServiceSOAP12",
                      targetNamespace = "urn://de/rwth/idsg/sensor/change",
                      wsdlLocation = "file:/Users/sgokay/git/steve/src/main/webapp/SensorChangeService.wsdl",
                      endpointInterface = "de.rwth.idsg.sensor.change.ChangeService")
                      
public class ChangeServiceImpl implements ChangeService {

    private static final Logger LOG = Logger.getLogger(ChangeServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see de.rwth.idsg.sensor.change.ChangeService#changeConfiguration(de.rwth.idsg.sensor.change.ChangeConfigurationRequest  parameters ,)java.lang.String  chargeBoxIdentity )*
     */
    public de.rwth.idsg.sensor.change.ChangeConfigurationResponse changeConfiguration(ChangeConfigurationRequest parameters,java.lang.String chargeBoxIdentity) { 
        LOG.info("Executing operation changeConfiguration");
        System.out.println(parameters);
        System.out.println(chargeBoxIdentity);
        try {
            de.rwth.idsg.sensor.change.ChangeConfigurationResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see de.rwth.idsg.sensor.change.ChangeService#changeStatus(de.rwth.idsg.sensor.change.ChangeStatusRequest  parameters ,)java.lang.String  chargeBoxIdentity )*
     */
    public de.rwth.idsg.sensor.change.ChangeStatusResponse changeStatus(ChangeStatusRequest parameters,java.lang.String chargeBoxIdentity) { 
        LOG.info("Executing operation changeStatus");
        System.out.println(parameters);
        System.out.println(chargeBoxIdentity);
        try {
            de.rwth.idsg.sensor.change.ChangeStatusResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
