package ocpp.cp._2012._06;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Sep 18 16:11:00 CEST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "urn://Ocpp/Cp/2012/06/", name = "ChargePointService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChargePointService {

    @WebResult(name = "clearCacheResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/ClearCache", output = "/ClearCacheResponse")
    @WebMethod(operationName = "ClearCache", action = "/ClearCache")
    public ClearCacheResponse clearCache(
        @WebParam(partName = "parameters", name = "clearCacheRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ClearCacheRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "getLocalListVersionResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/GetLocalListVersion", output = "/GetLocalListVersionResponse")
    @WebMethod(operationName = "GetLocalListVersion", action = "/GetLocalListVersion")
    public GetLocalListVersionResponse getLocalListVersion(
        @WebParam(partName = "parameters", name = "getLocalListVersionRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        GetLocalListVersionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "cancelReservationResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/CancelReservation", output = "/CancelReservationResponse")
    @WebMethod(operationName = "CancelReservation", action = "/CancelReservation")
    public CancelReservationResponse cancelReservation(
        @WebParam(partName = "parameters", name = "cancelReservationRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        CancelReservationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "updateFirmwareResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/UpdateFirmware", output = "/UpdateFirmwareResponse")
    @WebMethod(operationName = "UpdateFirmware", action = "/UpdateFirmware")
    public UpdateFirmwareResponse updateFirmware(
        @WebParam(partName = "parameters", name = "updateFirmwareRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        UpdateFirmwareRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "getConfigurationResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/GetConfiguration", output = "/GetConfigurationResponse")
    @WebMethod(operationName = "GetConfiguration", action = "/GetConfiguration")
    public GetConfigurationResponse getConfiguration(
        @WebParam(partName = "parameters", name = "getConfigurationRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        GetConfigurationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "remoteStopTransactionResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/RemoteStopTransaction", output = "/RemoteStopTransactionResponse")
    @WebMethod(operationName = "RemoteStopTransaction", action = "/RemoteStopTransaction")
    public RemoteStopTransactionResponse remoteStopTransaction(
        @WebParam(partName = "parameters", name = "remoteStopTransactionRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        RemoteStopTransactionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "changeAvailabilityResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/ChangeAvailability", output = "/ChangeAvailabilityResponse")
    @WebMethod(operationName = "ChangeAvailability", action = "/ChangeAvailability")
    public ChangeAvailabilityResponse changeAvailability(
        @WebParam(partName = "parameters", name = "changeAvailabilityRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ChangeAvailabilityRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "unlockConnectorResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/UnlockConnector", output = "/UnlockConnectorResponse")
    @WebMethod(operationName = "UnlockConnector", action = "/UnlockConnector")
    public UnlockConnectorResponse unlockConnector(
        @WebParam(partName = "parameters", name = "unlockConnectorRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        UnlockConnectorRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "dataTransferResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/DataTransfer", output = "/DataTransferResponse")
    @WebMethod(operationName = "DataTransfer", action = "/DataTransfer")
    public DataTransferResponse dataTransfer(
        @WebParam(partName = "parameters", name = "dataTransferRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        DataTransferRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "reserveNowResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/ReserveNow", output = "/ReserveNowResponse")
    @WebMethod(operationName = "ReserveNow", action = "/ReserveNow")
    public ReserveNowResponse reserveNow(
        @WebParam(partName = "parameters", name = "reserveNowRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ReserveNowRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "resetResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/Reset", output = "/ResetResponse")
    @WebMethod(operationName = "Reset", action = "/Reset")
    public ResetResponse reset(
        @WebParam(partName = "parameters", name = "resetRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ResetRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "sendLocalListResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/SendLocalList", output = "/SendLocalListResponse")
    @WebMethod(operationName = "SendLocalList", action = "/SendLocalList")
    public SendLocalListResponse sendLocalList(
        @WebParam(partName = "parameters", name = "sendLocalListRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        SendLocalListRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "remoteStartTransactionResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/RemoteStartTransaction", output = "/RemoteStartTransactionResponse")
    @WebMethod(operationName = "RemoteStartTransaction", action = "/RemoteStartTransaction")
    public RemoteStartTransactionResponse remoteStartTransaction(
        @WebParam(partName = "parameters", name = "remoteStartTransactionRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        RemoteStartTransactionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "getDiagnosticsResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/GetDiagnostics", output = "/GetDiagnosticsResponse")
    @WebMethod(operationName = "GetDiagnostics", action = "/GetDiagnostics")
    public GetDiagnosticsResponse getDiagnostics(
        @WebParam(partName = "parameters", name = "getDiagnosticsRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        GetDiagnosticsRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "changeConfigurationResponse", targetNamespace = "urn://Ocpp/Cp/2012/06/", partName = "parameters")
    @Action(input = "/ChangeConfiguration", output = "/ChangeConfigurationResponse")
    @WebMethod(operationName = "ChangeConfiguration", action = "/ChangeConfiguration")
    public ChangeConfigurationResponse changeConfiguration(
        @WebParam(partName = "parameters", name = "changeConfigurationRequest", targetNamespace = "urn://Ocpp/Cp/2012/06/")
        ChangeConfigurationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2012/06/", header = true)
        java.lang.String chargeBoxIdentity
    );
}
