package de.rwth.idsg.steve.gateway.oicp.model;

public enum PlugType {
    SMALL_PADDLE_INDUCTIVE,
    LARGE_PADDLE_INDUCTIVE,
    AVCON_CONNECTOR,
    TESLA_CONNECTOR,
    NEMA_5_20,
    TYPE_E_FRENCH_STANDARD,
    TYPE_F_SCHUKO,
    TYPE_G_BRITISH_STANDARD,
    TYPE_J_SWISS_STANDARD,
    TYPE_1_CONNECTOR_CABLE_ATTACHED,
    TYPE_2_OUTLET,
    TYPE_2_CONNECTOR_CABLE_ATTACHED,
    TYPE_3_OUTLET,
    IEC_60309_SINGLE_PHASE,
    IEC_60309_THREE_PHASE,
    CCS_COMBO_2_PLUG_CABLE_ATTACHED,
    CCS_COMBO_1_PLUG_CABLE_ATTACHED,
    CHADEMO
}