package de.rwth.idsg.steve.css.v12;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.soap.Addressing;

/**
 * This class was generated by Apache CXF 2.3.1
 * Mon Jul 29 22:10:30 CEST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "urn://Ocpp/Cs/2010/08/", name = "CentralSystemService")
//@Addressing(enabled=true, required=true) //TODO: this is new
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CentralSystemService {

    @WebResult(name = "bootNotificationResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/BootNotification")
    @WebMethod(operationName = "BootNotification", action = "/BootNotification")
    public BootNotificationResponse bootNotification(
        @WebParam(partName = "parameters", name = "bootNotificationRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        BootNotificationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "firmwareStatusNotificationResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/FirmwareStatusNotification")
    @WebMethod(operationName = "FirmwareStatusNotification", action = "/FirmwareStatusNotification")
    public FirmwareStatusNotificationResponse firmwareStatusNotification(
        @WebParam(partName = "parameters", name = "firmwareStatusNotificationRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        FirmwareStatusNotificationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "statusNotificationResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/StatusNotification")
    @WebMethod(operationName = "StatusNotification", action = "/StatusNotification")
    public StatusNotificationResponse statusNotification(
        @WebParam(partName = "parameters", name = "statusNotificationRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        StatusNotificationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "meterValuesResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/MeterValues")
    @WebMethod(operationName = "MeterValues", action = "/MeterValues")
    public MeterValuesResponse meterValues(
        @WebParam(partName = "parameters", name = "meterValuesRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        MeterValuesRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "diagnosticsStatusNotificationResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/DiagnosticsStatusNotification")
    @WebMethod(operationName = "DiagnosticsStatusNotification", action = "/DiagnosticsStatusNotification")
    public DiagnosticsStatusNotificationResponse diagnosticsStatusNotification(
        @WebParam(partName = "parameters", name = "diagnosticsStatusNotificationRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        DiagnosticsStatusNotificationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "authorizeResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/Authorize")
    @WebMethod(operationName = "Authorize", action = "/Authorize")
    public AuthorizeResponse authorize(
        @WebParam(partName = "parameters", name = "authorizeRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        AuthorizeRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "heartbeatResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/Heartbeat")
    @WebMethod(operationName = "Heartbeat", action = "/Heartbeat")
    public HeartbeatResponse heartbeat(
        @WebParam(partName = "parameters", name = "heartbeatRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        HeartbeatRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "stopTransactionResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/StopTransaction")
    @WebMethod(operationName = "StopTransaction", action = "/StopTransaction")
    public StopTransactionResponse stopTransaction(
        @WebParam(partName = "parameters", name = "stopTransactionRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        StopTransactionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "startTransactionResponse", targetNamespace = "urn://Ocpp/Cs/2010/08/", partName = "parameters")
    @Action(input = "/StartTransaction")
    @WebMethod(operationName = "StartTransaction", action = "/StartTransaction")
    public StartTransactionResponse startTransaction(
        @WebParam(partName = "parameters", name = "startTransactionRequest", targetNamespace = "urn://Ocpp/Cs/2010/08/")
        StartTransactionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cs/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );
}
