package ocpp.cp._2010._08;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.3.1
 * Wed Sep 18 16:19:42 CEST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "urn://Ocpp/Cp/2010/08/", name = "ChargePointService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ChargePointService {

    @WebResult(name = "getDiagnosticsResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/GetDiagnostics")
    @WebMethod(operationName = "GetDiagnostics", action = "/GetDiagnostics")
    public GetDiagnosticsResponse getDiagnostics(
        @WebParam(partName = "parameters", name = "getDiagnosticsRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        GetDiagnosticsRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "remoteStartTransactionResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/RemoteStartTransaction")
    @WebMethod(operationName = "RemoteStartTransaction", action = "/RemoteStartTransaction")
    public RemoteStartTransactionResponse remoteStartTransaction(
        @WebParam(partName = "parameters", name = "remoteStartTransactionRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        RemoteStartTransactionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "updateFirmwareResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/UpdateFirmware")
    @WebMethod(operationName = "UpdateFirmware", action = "/UpdateFirmware")
    public UpdateFirmwareResponse updateFirmware(
        @WebParam(partName = "parameters", name = "updateFirmwareRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        UpdateFirmwareRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "changeAvailabilityResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/ChangeAvailability")
    @WebMethod(operationName = "ChangeAvailability", action = "/ChangeAvailability")
    public ChangeAvailabilityResponse changeAvailability(
        @WebParam(partName = "parameters", name = "changeAvailabilityRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        ChangeAvailabilityRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "clearCacheResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/ClearCache")
    @WebMethod(operationName = "ClearCache", action = "/ClearCache")
    public ClearCacheResponse clearCache(
        @WebParam(partName = "parameters", name = "clearCacheRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        ClearCacheRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "resetResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/Reset")
    @WebMethod(operationName = "Reset", action = "/Reset")
    public ResetResponse reset(
        @WebParam(partName = "parameters", name = "resetRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        ResetRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "remoteStopTransactionResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/RemoteStopTransaction")
    @WebMethod(operationName = "RemoteStopTransaction", action = "/RemoteStopTransaction")
    public RemoteStopTransactionResponse remoteStopTransaction(
        @WebParam(partName = "parameters", name = "remoteStopTransactionRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        RemoteStopTransactionRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "unlockConnectorResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/UnlockConnector")
    @WebMethod(operationName = "UnlockConnector", action = "/UnlockConnector")
    public UnlockConnectorResponse unlockConnector(
        @WebParam(partName = "parameters", name = "unlockConnectorRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        UnlockConnectorRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );

    @WebResult(name = "changeConfigurationResponse", targetNamespace = "urn://Ocpp/Cp/2010/08/", partName = "parameters")
    @Action(input = "/ChangeConfiguration")
    @WebMethod(operationName = "ChangeConfiguration", action = "/ChangeConfiguration")
    public ChangeConfigurationResponse changeConfiguration(
        @WebParam(partName = "parameters", name = "changeConfigurationRequest", targetNamespace = "urn://Ocpp/Cp/2010/08/")
        ChangeConfigurationRequest parameters,
        @WebParam(partName = "ChargeBoxIdentity", name = "chargeBoxIdentity", targetNamespace = "urn://Ocpp/Cp/2010/08/", header = true)
        java.lang.String chargeBoxIdentity
    );
}
